comment filestore
Signed-off-by: Piotr Pawłowski <ppawl@google.com>

diff --git a/.github/workflows/build_tests.yaml b/.github/workflows/build_tests.yaml
--- a/.github/workflows/build_tests.yaml
+++ b/.github/workflows/build_tests.yaml
@@ -72,14 +72,14 @@ jobs:
         python3 xpk.py storage create $STORAGE_NAME --cluster=$TPU_CLUSTER_NAME --zone=us-central2-b --type=gcsfuse \
         --auto-mount=true \
         --mount-point='/test-mount-point' --readonly=false --manifest='./tests/data/pv-pvc-templates.yaml'
-    - name: Fill Filestore manifest file
-      run: |
-        sed -i 's/PROJECT_NAME/${{secrets.PROJECT_NAME}}/g;  s/ZONE/us-central2-b/g; s/INSTANCE_NAME/${{secrets.INSTANCE_NAME}}/g; s/VOL_NAME/${{secrets.VOL_NAME}}/g; s/IP_ADDRESS/${{secrets.IP_ADDRESS}}/g' ./tests/data/fs-manifest.yaml 
-    - name: Create auto-mount GCP Filestore Storage instance
-      run: |
-        python3 xpk.py storage create $FS_STORAGE_NAME --cluster=$TPU_CLUSTER_NAME --zone=us-central2-b --type=gcpfilestore \
-        --auto-mount=true \
-        --mount-point='/fs-test-mount-point' --readonly=false --manifest='./tests/data/fs-manifest.yaml'
+    # - name: Fill Filestore manifest file
+    #   run: |
+    #     sed -i 's/PROJECT_NAME/${{secrets.PROJECT_NAME}}/g;  s/ZONE/us-central2-b/g; s/INSTANCE_NAME/${{secrets.INSTANCE_NAME}}/g; s/VOL_NAME/${{secrets.VOL_NAME}}/g; s/IP_ADDRESS/${{secrets.IP_ADDRESS}}/g' ./tests/data/fs-manifest.yaml 
+    # - name: Create auto-mount GCP Filestore Storage instance
+    #   run: |
+    #     python3 xpk.py storage create $FS_STORAGE_NAME --cluster=$TPU_CLUSTER_NAME --zone=us-central2-b --type=gcpfilestore \
+    #     --auto-mount=true \
+    #     --mount-point='/fs-test-mount-point' --readonly=false --manifest='./tests/data/fs-manifest.yaml'
     - name: List and verify existing Storages
       run: python3 xpk.py storage list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b | tee output.txt | grep 'test-storage' || (echo 'No storage found' && cat output.txt && exit 1)
     - name: Create test script to execute in workloads
@@ -108,18 +108,18 @@ jobs:
       run: grep 'Hello world from a Github Action CI/CD test script!' $RANDOM_SEED.txt
     - name: Wait for Pathways workload completion and confirm it succeeded
       run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $PATHWAYS_WORKLOAD_NAME --timeout 300
-    - name: Run workload to write file on filestore
-      run : python3 xpk.py workload create-pathways --workload fs-write-workload --command "echo 'Test text message' > /fs-test-mount-point/$RANDOM_SEED/text.txt" --cluster $TPU_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
-    - name: Wait for writer workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion fs-write-workload --timeout 300
-    - name: Run workload to read file on filestore
-      run : python3 xpk.py workload create-pathways --workload fs-read-workload --command "cat /fs-test-mount-point/$RANDOM_SEED/text.txt | grep 'Test text message' || (echo 'Writing to filestore failed' && exit 1)" --cluster $TPU_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
-    - name: Wait for reader workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion fs-read-workload --timeout 300
-    - name: Run workload to delete file on filestore
-      run : python3 xpk.py workload create-pathways --workload fs-delete-workload --command "rm -rf /fs-test-mount-point/$RANDOM_SEED" --cluster $TPU_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
-    - name: Wait for reader workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion fs-delete-workload --timeout 300
+    # - name: Run workload to write file on filestore
+    #   run : python3 xpk.py workload create-pathways --workload fs-write-workload --command "echo 'Test text message' > /fs-test-mount-point/$RANDOM_SEED/text.txt" --cluster $TPU_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+    # - name: Wait for writer workload completion and confirm it succeeded
+    #   run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion fs-write-workload --timeout 300
+    # - name: Run workload to read file on filestore
+    #   run : python3 xpk.py workload create-pathways --workload fs-read-workload --command "cat /fs-test-mount-point/$RANDOM_SEED/text.txt | grep 'Test text message' || (echo 'Writing to filestore failed' && exit 1)" --cluster $TPU_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+    # - name: Wait for reader workload completion and confirm it succeeded
+    #   run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion fs-read-workload --timeout 300
+    # - name: Run workload to delete file on filestore
+    #   run : python3 xpk.py workload create-pathways --workload fs-delete-workload --command "rm -rf /fs-test-mount-point/$RANDOM_SEED" --cluster $TPU_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+    # - name: Wait for reader workload completion and confirm it succeeded
+    #   run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion fs-delete-workload --timeout 300
     - name: List out the workloads on the cluster
       run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b
     - name: Delete the workload on the cluster
