fix: fuse test messages

diff --git a/.github/workflows/reusable_fuse_tests.yaml b/.github/workflows/reusable_fuse_tests.yaml
--- a/.github/workflows/reusable_fuse_tests.yaml
+++ b/.github/workflows/reusable_fuse_tests.yaml
@@ -86,25 +86,25 @@ jobs:
       run: xpk --help
     - name: Authenticate Docker
       run: gcloud auth configure-docker --quiet
-    - name: Attach auto-mount GCP Filestore Storage instance
+    - name: Attach auto-mount GCS FUSE Storage instance
       run: python3 xpk.py storage attach $FUSE_STORAGE_NAME --cluster=${{inputs.cluster-name}} --zone=${{inputs.zone}} --type=gcsfuse --auto-mount=true --mount-point='/fuse-test-mount-point' --readonly=false --size=1 --bucket=$FUSE_BUCKET_NAME
     - name: List and verify existing Storages
       run: python3 xpk.py storage list --cluster ${{inputs.cluster-name}} --zone=${{inputs.zone}} | tee output.txt | grep $FUSE_STORAGE_NAME || (echo 'No storage found' && exit 143)
     - name: Verify VolumeBundle created
       run: kubectl get volumebundle $FUSE_STORAGE_NAME -o jsonpath='{.spec.containerVolumeMounts[0].mountPath}' | grep '/fuse-test-mount-point'
-    - name: Run workload to write file on filestore
-      run : python3 xpk.py workload create --workload $FUSE_WRITE_WORKLOAD --docker-image='marketplace.gcr.io/google/ubuntu2004' --command "mkdir /fuse-test-mount-point/$RANDOM_SEED/ && echo 'Test text message' > /fuse-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Writing to filestore failed' && exit 143)" --cluster ${{inputs.cluster-name}} --tpu-type=${{inputs.tpu-type}} --zone ${{inputs.location}}
+    - name: Run workload to write file on storage
+      run : python3 xpk.py workload create --workload $FUSE_WRITE_WORKLOAD --docker-image='marketplace.gcr.io/google/ubuntu2004' --command "mkdir /fuse-test-mount-point/$RANDOM_SEED/ && echo 'Test text message' > /fuse-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Writing to storage failed' && exit 143)" --cluster ${{inputs.cluster-name}} --tpu-type=${{inputs.tpu-type}} --zone ${{inputs.location}}
     - name: Wait for writer workload completion and confirm it succeeded
       run: python3 xpk.py workload list --cluster ${{inputs.cluster-name}} --zone=${{inputs.zone}} --wait-for-job-completion $FUSE_WRITE_WORKLOAD --timeout 300
-    - name: Run workload to read file on filestore
-      run : python3 xpk.py workload create --workload $FUSE_READ_WORKLOAD --command "grep 'Test text message' /fuse-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Reading from filestore failed' && exit 143)" --cluster ${{inputs.cluster-name}} --tpu-type=${{inputs.tpu-type}} --zone ${{inputs.location}}
+    - name: Run workload to read file on storage
+      run : python3 xpk.py workload create --workload $FUSE_READ_WORKLOAD --command "grep 'Test text message' /fuse-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Reading from storage failed' && exit 143)" --cluster ${{inputs.cluster-name}} --tpu-type=${{inputs.tpu-type}} --zone ${{inputs.location}}
     - name: Wait for reader workload completion and confirm it succeeded
       run: python3 xpk.py workload list --cluster ${{inputs.cluster-name}} --zone=${{inputs.zone}} --wait-for-job-completion $FUSE_READ_WORKLOAD --timeout 300
     - name: Create batch-read.sh script
       run: |
         cat <<EOF > batch-read.sh
         #!/bin/bash
-        grep 'Test text message' /fuse-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Reading from filestore failed' && exit 143)
+        grep 'Test text message' /fuse-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Reading from storage failed' && exit 143)
         EOF
     - name: Run a batch-read job on the cluster
       run: python3 xpk.py batch --cluster ${{inputs.cluster-name}} --zone=${{inputs.zone}} batch-read.sh | tee batch-read.log
@@ -139,7 +139,7 @@ jobs:
       run: python3 xpk.py shell stop --cluster ${{inputs.cluster-name}} --zone=${{inputs.zone}}
     - name: Delete create-shell.exp file
       run: rm create-shell.exp
-    - name: Run workload to delete file on filestore
+    - name: Run workload to delete file on storage
       run : python3 xpk.py workload create --workload $FUSE_DELETE_WORKLOAD --command "rm -rf /fuse-test-mount-point/$RANDOM_SEED/test.txt || exit 143" --cluster ${{inputs.cluster-name}} --tpu-type=${{inputs.tpu-type}} --zone ${{inputs.location}}
     - name: Wait for delete workload completion and confirm it succeeded
       run: python3 xpk.py workload list --cluster ${{inputs.cluster-name}} --zone=${{inputs.zone}} --wait-for-job-completion $FUSE_DELETE_WORKLOAD --timeout 300
