add tests
Signed-off-by: Piotr Pawłowski <ppawl@google.com>

diff --git a/.github/workflows/storage_tests.yaml b/.github/workflows/storage_tests.yaml
--- a/.github/workflows/storage_tests.yaml
+++ b/.github/workflows/storage_tests.yaml
@@ -12,7 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License
 
-name: Build Tests
+name: Storage Tests
 
 on:
   push:
@@ -107,12 +107,11 @@ jobs:
     - name: Delete the cluster created
       if: always()
       run: python3 xpk.py cluster delete --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b
-
-  cluster-create-and-delete:
+  
+  filestore-create:
     runs-on: [ubuntu-20.04]
-    if: false
     concurrency: # We support one build or nightly test to run at a time currently.
-      group: build-test-cluster-group
+      group: filestore-test-group
       cancel-in-progress: false
     steps:
     - uses: actions/checkout@v4
@@ -140,57 +139,45 @@ jobs:
       run: |
         pip install .
         xpk --help
-    - name: Create a Pathways-enabled XPK Cluster with 2x v4-8 nodepools. Larger num-nodes to avoid master resizing.
-      run: |
-        python3 xpk.py cluster create-pathways --cluster $TPU_CLUSTER_NAME --tpu-type=v4-8  --num-slices=2 \
-        --zone=us-central2-b --default-pool-cpu-machine-type=n1-standard-16 --default-pool-cpu-num-nodes=16 \
-        --reservation='${{ secrets.GCP_TPU_V4_RESERVATION }}' --enable-workload-identity --enable-gcsfuse-csi-driver --enable-gcpfilestore-csi-driver --custom-cluster-arguments="${PW_CLUSTER_ARGUMENTS}"
-
     - name: Authenticate Docker
       run: gcloud auth configure-docker --quiet
-    - name: Create auto-mount Storage instance
+    - name: Create a XPK Cluster with 2x v4-8 nodepools. Larger num-nodes to avoid master resizing.
       run: |
-        python3 xpk.py storage create $STORAGE_NAME --cluster=$TPU_CLUSTER_NAME --zone=us-central2-b --type=gcsfuse \
-        --auto-mount=true \
-        --mount-point='/test-mount-point' --readonly=false --manifest='./tests/data/pv-pvc-templates.yaml'
+        python3 xpk.py cluster create --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8  --num-slices=0 \
+        --zone=europe-west4-a --default-pool-cpu-machine-type=n1-standard-16 --default-pool-cpu-num-nodes=16 \
+        --spot --enable-workload-identity --enable-gcpfilestore-csi-driver --custom-cluster-arguments="${CLUSTER_ARGUMENTS}"
+    - name: Create auto-mount GCP Filestore Storage instance
+      run: |
+        python3 xpk.py storage create $FS_STORAGE_NAME --cluster=$TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a --type=gcpfilestore \
+        --auto-mount=true --vol=vol1 --size=1024 --tier=BASIC_HDD \
+        --mount-point='/fs-test-mount-point' --readonly=false
     - name: List and verify existing Storages
-      run: python3 xpk.py storage list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b | tee output.txt | grep 'test-storage' || (echo 'No storage found' && cat output.txt && exit 1)
-    - name: Create test script to execute in workloads
-      run: |
-        echo -e \
-        '#!/bin/bash \n
-        echo "Hello world from a test script!"
-        cd ~/../test-mount-point && echo "Hello world from a Github Action CI/CD test script!" > '$RANDOM_SEED'.txt' \
-        > test.sh
-    - name: Run a base-docker-image workload
-      run: |
-        python3 xpk.py workload create --cluster $TPU_CLUSTER_NAME --workload $WORKLOAD_NAME  --command "bash test.sh"  \
-        --tpu-type=v4-8 --num-slices=2 --zone=us-central2-b
-    - name: Run xpk inspector with the workload created above
-      run: python3 xpk.py inspector --cluster $TPU_CLUSTER_NAME --zone=us-central2-b  --workload $WORKLOAD_NAME
-    - name: Wait for workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $WORKLOAD_NAME --timeout 300
-    - name: Run a Pathways workload on Ubuntu base image
-      run: |
-        python3 xpk.py workload create-pathways --cluster $TPU_CLUSTER_NAME --workload $PATHWAYS_WORKLOAD_NAME \
-        --docker-image='marketplace.gcr.io/google/ubuntu2004' --tpu-type=v4-8 --num-slices=2 --zone=us-central2-b \
-        --command "echo \"Hello world from a test script! \""
-    - name: Verify if the file was created in the GCS bucket
-      run: gsutil cp gs://xpk-ci-cd-tests/$RANDOM_SEED.txt .
-    - name: Check if the file contains desired content
-      run: grep 'Hello world from a Github Action CI/CD test script!' $RANDOM_SEED.txt
-    - name: Wait for Pathways workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $PATHWAYS_WORKLOAD_NAME --timeout 300
-    - name: List out the workloads on the cluster
-      run: python3 xpk.py workload list --cluster $TPU_CLUSTER_NAME --zone=us-central2-b
-    - name: Delete the workload on the cluster
-      run: python3 xpk.py workload delete --workload $WORKLOAD_NAME --cluster $TPU_CLUSTER_NAME --zone=us-central2-b
-    - name: Delete the Pathways workload on the cluster
-      run: python3 xpk.py workload delete --workload $PATHWAYS_WORKLOAD_NAME --cluster $TPU_CLUSTER_NAME --zone=us-central2-b
-    - name: Delete created GCS file
-      run: gsutil rm gs://xpk-ci-cd-tests/$RANDOM_SEED.txt
-    - name: Delete existing Storage
-      run: python3 xpk.py storage delete $STORAGE_NAME  --cluster $TPU_CLUSTER_NAME --zone=us-central2-b
+      run: python3 xpk.py storage list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a | tee output.txt | grep $FS_STORAGE_NAME || (echo 'No storage found' && exit 143)
+    - name: List and verify existing Filestore instances.
+      run: gcloud filestore instances list --zone=europe-west4-a | grep $FS_STORAGE_NAME
+    - name: Run workload to write file on filestore
+      run : python3 xpk.py workload create --workload $FS_WRITE_WORKLOAD --command "mkdir /fs-test-mount-point/$RANDOM_SEED/ && echo 'Test text message' > /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Writing to filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+    - name: Wait for writer workload completion and confirm it succeeded
+      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a --wait-for-job-completion $FS_WRITE_WORKLOAD --timeout 300
+    - name: Run workload to read file on filestore
+      run : python3 xpk.py workload create --workload $FS_READ_WORKLOAD --command "cat /fs-test-mount-point/$RANDOM_SEED/test.txt | grep 'Test text message' || (echo 'Reading from filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+    - name: Wait for reader workload completion and confirm it succeeded
+      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a --wait-for-job-completion $FS_READ_WORKLOAD --timeout 300
+    - name: Run workload to delete file on filestore
+      run : python3 xpk.py workload create --workload $FS_DELETE_WORKLOAD --command "rm -rf /fs-test-mount-point/$RANDOM_SEED/test.txt || exit 143" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+    - name: Wait for delete workload completion and confirm it succeeded
+      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a --wait-for-job-completion $FS_DELETE_WORKLOAD --timeout 300
+    - name: Delete the filestore instance
+      run: gcloud filestore instances delete $FS_STORAGE_NAME --zone=europe-west4-a --force 
+    - name: Delete the writer workload on the cluster
+      if: always()
+      run: python3 xpk.py workload delete --workload $FS_WRITE_WORKLOAD --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a
+    - name: Delete the reader workload on the cluster
+      if: always()
+      run: python3 xpk.py workload delete --workload $FS_READ_WORKLOAD --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a
+    - name: Delete the delete workload on the cluster
+      if: always()
+      run: python3 xpk.py workload delete --workload $FS_DELETE_WORKLOAD --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a
     - name: Delete the cluster created
       if: always()
-      run: python3 xpk.py cluster delete --cluster $TPU_CLUSTER_NAME --zone=us-central2-b
+      run: python3 xpk.py cluster delete --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=europe-west4-a
