Test

diff --git a/.github/workflows/storage_tests.yaml b/.github/workflows/storage_tests.yaml
--- a/.github/workflows/storage_tests.yaml
+++ b/.github/workflows/storage_tests.yaml
@@ -15,6 +15,7 @@
 name: Storage Tests
 
 on:
+  workflow_dispatch:
   push:
     branches: ["main"]
   pull_request: # By default this runs for types assigned, opened and synchronize.
@@ -77,19 +78,22 @@ jobs:
         --auto-mount=true \
         --mount-point='/fs-test-mount-point' --readonly=false --manifest='./tests/data/fs-manifest.yaml'
     - name: List and verify existing Storages
-      run: python3 xpk.py storage list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b | tee output.txt | grep $FS_STORAGE_NAME || (echo 'No storage found' && exit 143)
-    - name: Run workload to write file on filestore
-      run : python3 xpk.py workload create --workload $FS_WRITE_WORKLOAD --docker-image='marketplace.gcr.io/google/ubuntu2004' --command "mkdir /fs-test-mount-point/$RANDOM_SEED/ && echo 'Test text message' > /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Writing to filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
-    - name: Wait for writer workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $FS_WRITE_WORKLOAD --timeout 300
-    - name: Run workload to read file on filestore
-      run : python3 xpk.py workload create --workload $FS_READ_WORKLOAD --command "grep 'Test text message' /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Reading from filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
-    - name: Wait for reader workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $FS_READ_WORKLOAD --timeout 300
-    - name: Run workload to delete file on filestore
-      run : python3 xpk.py workload create --workload $FS_DELETE_WORKLOAD --command "rm -rf /fs-test-mount-point/$RANDOM_SEED/test.txt || exit 143" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
-    - name: Wait for delete workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $FS_DELETE_WORKLOAD --timeout 300
+      run: |
+        python3 xpk.py storage list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b | tee output.txt | grep $FS_STORAGE_NAME || (echo 'No storage found' && exit 143)
+        kubectl get pv -o yaml
+        kubectl get pvc -o yaml
+#    - name: Run workload to write file on filestore
+#      run : python3 xpk.py workload create --workload $FS_WRITE_WORKLOAD --docker-image='marketplace.gcr.io/google/ubuntu2004' --command "mkdir /fs-test-mount-point/$RANDOM_SEED/ && echo 'Test text message' > /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Writing to filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+#    - name: Wait for writer workload completion and confirm it succeeded
+#      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $FS_WRITE_WORKLOAD --timeout 300
+#    - name: Run workload to read file on filestore
+#      run : python3 xpk.py workload create --workload $FS_READ_WORKLOAD --command "grep 'Test text message' /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Reading from filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+#    - name: Wait for reader workload completion and confirm it succeeded
+#      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $FS_READ_WORKLOAD --timeout 300
+#    - name: Run workload to delete file on filestore
+#      run : python3 xpk.py workload create --workload $FS_DELETE_WORKLOAD --command "rm -rf /fs-test-mount-point/$RANDOM_SEED/test.txt || exit 143" --cluster $TPU_FILESTORE_CLUSTER_NAME --tpu-type=v4-8 --zone us-central2
+#    - name: Wait for delete workload completion and confirm it succeeded
+#      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME --zone=us-central2-b --wait-for-job-completion $FS_DELETE_WORKLOAD --timeout 300
     - name: Delete storage
       run: python3 xpk.py storage delete $FS_STORAGE_NAME --zone=us-central2-b --cluster=$TPU_FILESTORE_CLUSTER_NAME
     - name: Delete the writer workload on the cluster
@@ -149,19 +153,22 @@ jobs:
         --auto-mount=true --vol=vol1 --size=1024 --tier=BASIC_HDD \
         --mount-point='/fs-test-mount-point' --readonly=false
     - name: List and verify existing Storages
-      run: python3 xpk.py storage list --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --zone=us-central2-b | tee output.txt | grep $FS_STORAGE_NAME || (echo 'No storage found' && exit 143)
-    - name: Run workload to write file on filestore
-      run : python3 xpk.py workload create --workload $FS_WRITE_WORKLOAD --num-slices=1 --docker-image='marketplace.gcr.io/google/ubuntu2004' --command "mkdir /fs-test-mount-point/$RANDOM_SEED/ && echo 'Test text message' > /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Writing to filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --tpu-type=v4-8 --zone us-central2-b
-    - name: Wait for writer workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --zone=us-central2-b --wait-for-job-completion $FS_WRITE_WORKLOAD --timeout 300
-    - name: Run workload to read file on filestore
-      run : python3 xpk.py workload create --workload $FS_READ_WORKLOAD --num-slices=1 --command "grep 'Test text message' /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Reading from filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --tpu-type=v4-8 --zone us-central2-b
-    - name: Wait for reader workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --zone=us-central2-b --wait-for-job-completion $FS_READ_WORKLOAD --timeout 300
-    - name: Run workload to delete file on filestore
-      run : python3 xpk.py workload create --workload $FS_DELETE_WORKLOAD --command "rm -rf /fs-test-mount-point/$RANDOM_SEED/test.txt || exit 143" --num-slices=1 --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --tpu-type=v4-8 --zone us-central2-b
-    - name: Wait for delete workload completion and confirm it succeeded
-      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --zone=us-central2-b --wait-for-job-completion $FS_DELETE_WORKLOAD --timeout 300
+      run: |
+        python3 xpk.py storage list --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --zone=us-central2-b | tee output.txt | grep $FS_STORAGE_NAME || (echo 'No storage found' && exit 143)
+        kubectl get pv -o yaml
+        kubectl get pvc -o yaml
+#    - name: Run workload to write file on filestore
+#      run : python3 xpk.py workload create --workload $FS_WRITE_WORKLOAD --num-slices=1 --docker-image='marketplace.gcr.io/google/ubuntu2004' --command "mkdir /fs-test-mount-point/$RANDOM_SEED/ && echo 'Test text message' > /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Writing to filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --tpu-type=v4-8 --zone us-central2-b
+#    - name: Wait for writer workload completion and confirm it succeeded
+#      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --zone=us-central2-b --wait-for-job-completion $FS_WRITE_WORKLOAD --timeout 300
+#    - name: Run workload to read file on filestore
+#      run : python3 xpk.py workload create --workload $FS_READ_WORKLOAD --num-slices=1 --command "grep 'Test text message' /fs-test-mount-point/$RANDOM_SEED/test.txt || (echo 'Reading from filestore failed' && exit 143)" --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --tpu-type=v4-8 --zone us-central2-b
+#    - name: Wait for reader workload completion and confirm it succeeded
+#      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --zone=us-central2-b --wait-for-job-completion $FS_READ_WORKLOAD --timeout 300
+#    - name: Run workload to delete file on filestore
+#      run : python3 xpk.py workload create --workload $FS_DELETE_WORKLOAD --command "rm -rf /fs-test-mount-point/$RANDOM_SEED/test.txt || exit 143" --num-slices=1 --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --tpu-type=v4-8 --zone us-central2-b
+#    - name: Wait for delete workload completion and confirm it succeeded
+#      run: python3 xpk.py workload list --cluster $TPU_FILESTORE_CLUSTER_NAME_CREATE --zone=us-central2-b --wait-for-job-completion $FS_DELETE_WORKLOAD --timeout 300
     - name: Delete storage
       run: python3 xpk.py storage delete $FS_STORAGE_NAME --zone=us-central2-b --cluster=$TPU_FILESTORE_CLUSTER_NAME_CREATE
     - name: Delete the filestore instance
